name: built_stream_generator
description: This library is the dev dependency.
version: 1.0.11
homepage: https://github.com/datvt9312/flutter_bloc/built_stream_generator

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  analyzer: ">=0.39.0 <0.42.0"
  build: ">=1.0.0 <2.0.0"
  built_collection: ">=4.0.0 <5.0.0"
  source_gen: 0.9.7+1
  built_stream:
    git:
      url: git://github.com/dao-wkm/built_stream.git

dev_dependencies:
  test: ^1.15.7
# dependency_overrides:
#   built_stream:
#     path: ../built_stream
